#############################################################
#
# Build the rtdimg root filesystem image
#
#############################################################

ifeq ($(BR2_TARGET_ROOTFS_RTDIMG),y)
#read other params here
RTDIMG_OPTS := -i $(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_FW_PATH)

ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_BASE_VERSION_500_MINI),y)
RTDIMG_OPTS += -v 500mini
endif

ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_BASE_VERSION_500),y)
RTDIMG_OPTS += -v 500
endif

ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_BASE_VERSION_500_PLUS),y)
RTDIMG_OPTS += -v 500plus
endif


ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_OVERWRITE_INSTALL),y)

ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_OVERWRITE_EBODA_INSTALL),y)
RTDIMG_OPTS += -a eboda
endif
ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_OVERWRITE_MEDE8ER_INSTALL),y)
endif
RTDIMG_OPTS += -a mede8er
endif

endif

ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_OVERWRITE_EBODA_HD500_RSSMENU),y)
RTDIMG_OPTS += -m hd500
endif
ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_OVERWRITE_EBODA_HD600_RSSMENU),y)
RTDIMG_OPTS += -m hd600
endif
ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_OVERWRITE_ACRYAN_RSSMENU),y)
RTDIMG_OPTS += -m acryan
endif
ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_OVERWRITE_OPLAY_RSSMENU),y)
RTDIMG_OPTS += -m oplay
endif
ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_OVERWRITE_EGREAT_RSSMENU),y)
RTDIMG_OPTS += -m egreat
endif

ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_OVERWRITE_EBODA_RSSMENU_DS),y)
RTDIMG_OPTS += -d eboda
endif

ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_OVERWRITE_EGREAT_RSSMENU_DS),y)
RTDIMG_OPTS += -d egreat
endif


ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_UPDATE_BINARIES),y)
RTDIMG_OPTS += -b
endif

ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_INSTALL_CB3PP_BINARIES),y)
RTDIMG_OPTS += -c
endif

ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_INSTALL_WEB_CONTROL_PANEL),y)
RTDIMG_OPTS += -w
endif

ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_MOVE_RSS_MENU),y)
RTDIMG_OPTS += -n
endif

ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_PATCH_WEATHER),y)
RTDIMG_OPTS += -e
endif

ifeq ($(BR2_TARGET_ROOTFS_RTDIMG_PLAYER_CUSTOM_OVERWRITE_ENCRYPT_RSSMENU_DS),y)
RTDIMG_OPTS += -e
endif

RTDIMG_OPTS += -t $(TARGET_DIR)

ifeq ($(BR2_LINUX_KERNEL),y)
RTDIMG_OPTS += -k $(BINARIES_DIR)
endif



SCRIPT := support/scripts/build-install-img
define ROOTFS_RTDIMG_CMD
	$(SCRIPT) $(RTDIMG_OPTS) 
endef

$(eval $(call ROOTFS_TARGET,rtdimg))
